// app/r/[slug]/page.tsx
//
// Public spectate page. Accessible WITHOUT login. The intentionally short
// /r/ prefix keeps share URLs compact (e.g. undergroundgallery.ai/r/k7d2qm)
// — easier to text, easier to read aloud, more memorable than /race/...
//
// IMPORTANT: this is the only race-related page that does NOT call
// getAuthContext(). It looks up by share_slug, requires is_public=true,
// and shows the same animation + result card a logged-in user would see.

import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { eq, and, isNull } from 'drizzle-orm';
import { db } from '@/lib/db';
import { raceResults, vehicles, users, photos } from '@/lib/db/schema';
import { SpectateClient } from '@/components/race/SpectateClient';
import { colors, fonts } from '@/lib/design';

export const dynamic = 'force-dynamic';
// Cache the rendered HTML for 60s so a viral share doesn't hammer the DB.
// The animation runs client-side anyway; only the metadata + initial paint
// come from this server render.
export const revalidate = 60;

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://undergroundgallery.ai';

const RACE_LABEL: Record<string, string> = {
  zero_sixty: '0–60',
  quarter_mile: 'Quarter Mile',
  half_mile: 'Half Mile',
  roll_40_140: '40–140 Roll',
  highway_pull: 'Highway Pull',
  dig: 'Dig Race',
  overall: 'Overall',
};

// ── Shared data loader ──────────────────────────────────────────────────

async function loadPublicRace(slug: string) {
  const [r] = await db
    .select()
    .from(raceResults)
    .where(
      and(
        eq(raceResults.shareSlug, slug),
        eq(raceResults.isPublic, true),
        isNull(raceResults.hiddenAt),
      ),
    )
    .limit(1);
  if (!r) return null;

  const [chalV] = r.challengerVehicleId
    ? await db
        .select({
          year: vehicles.year, make: vehicles.make, model: vehicles.model, trim: vehicles.trim,
          drivetrainOverride: vehicles.drivetrainOverride,
          primaryPhotoId: vehicles.primaryPhotoId,
        })
        .from(vehicles)
        .where(eq(vehicles.id, r.challengerVehicleId))
        .limit(1)
    : [null];
  const [oppV] = r.opponentVehicleId
    ? await db
        .select({
          year: vehicles.year, make: vehicles.make, model: vehicles.model, trim: vehicles.trim,
          drivetrainOverride: vehicles.drivetrainOverride,
          primaryPhotoId: vehicles.primaryPhotoId,
        })
        .from(vehicles)
        .where(eq(vehicles.id, r.opponentVehicleId))
        .limit(1)
    : [null];

  const [chalU] = await db
    .select({ callsign: users.callsign, isModerator: users.isModerator })
    .from(users)
    .where(eq(users.id, r.challengerUserId))
    .limit(1);
  const [oppU] = r.opponentUserId
    ? await db
        .select({ callsign: users.callsign, isModerator: users.isModerator })
        .from(users)
        .where(eq(users.id, r.opponentUserId))
        .limit(1)
    : [null];

  const [chalPhoto] = chalV?.primaryPhotoId
    ? await db.select({ urlFull: photos.urlFull }).from(photos).where(eq(photos.id, chalV.primaryPhotoId)).limit(1)
    : [null];
  const [oppPhoto] = oppV?.primaryPhotoId
    ? await db.select({ urlFull: photos.urlFull }).from(photos).where(eq(photos.id, oppV.primaryPhotoId)).limit(1)
    : [null];

  return { r, chalV, oppV, chalU, oppU, chalPhoto, oppPhoto };
}

// ── generateMetadata: this is what makes the link preview work ──────────

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const data = await loadPublicRace(slug);
  if (!data) return { title: 'Race not found · Underground Gallery' };

  const { r, chalV, oppV, chalU, oppU } = data;
  const chalCar = chalV ? `${chalV.year} ${chalV.make} ${chalV.model}` : '???';
  const oppCar = oppV ? `${oppV.year} ${oppV.make} ${oppV.model}` : '???';
  const chalCs = chalU?.callsign ?? '???';
  const oppCs = oppU?.callsign ?? '???';
  const winner =
    r.winnerVehicleId === r.challengerVehicleId
      ? chalCs
      : r.winnerVehicleId === r.opponentVehicleId
        ? oppCs
        : null;

  const title = winner
    ? `@${winner} took it · ${chalCar} vs ${oppCar}`
    : `Dead heat · ${chalCar} vs ${oppCar}`;
  const raceLabel = RACE_LABEL[r.raceType] ?? r.raceType;
  const description = winner
    ? `${raceLabel} · @${winner} won by ${(r.estimatedGap ?? 0).toFixed(2)}s. Underground Gallery — invite-only car community.`
    : `${raceLabel} · Photo finish between @${chalCs} and @${oppCs}. Underground Gallery — invite-only car community.`;

  // OG image is generated by /api/og/race/[slug]
  const ogImage = `${APP_URL}/api/og/race/${slug}`;
  const url = `${APP_URL}/r/${slug}`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: 'Underground Gallery',
      images: [{ url: ogImage, width: 1200, height: 630, alt: title }],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
    alternates: { canonical: url },
  };
}

// ── Page ─────────────────────────────────────────────────────────────────

export default async function PublicRacePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const data = await loadPublicRace(slug);
  if (!data) notFound();

  const { r, chalV, oppV, chalU, oppU, chalPhoto, oppPhoto } = data;
  const challengerLabel = chalV
    ? `${chalV.year} ${chalV.make} ${chalV.model}${chalV.trim ? ' ' + chalV.trim : ''}`
    : 'Unknown';
  const opponentLabel = oppV
    ? `${oppV.year} ${oppV.make} ${oppV.model}${oppV.trim ? ' ' + oppV.trim : ''}`
    : 'Unknown';

  const winner =
    r.winnerVehicleId === r.challengerVehicleId
      ? 'challenger'
      : r.winnerVehicleId === r.opponentVehicleId
        ? 'opponent'
        : 'tie';

  return (
    <div
      style={{
        minHeight: '100vh',
        background: colors.bg,
        color: colors.text,
        fontFamily: fonts.sans,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Top brand bar — minimal */}
      <header
        style={{
          padding: '20px 24px',
          borderBottom: `1px solid ${colors.border}`,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <a
          href="/"
          className="ug-mono"
          style={{
            fontSize: 11,
            letterSpacing: '0.4em',
            color: colors.accent,
            textDecoration: 'none',
            fontWeight: 700,
          }}
        >
          ∕∕ UNDERGROUND GALLERY
        </a>
        <a
          href="/"
          className="ug-btn ug-btn-ghost ug-pill"
          style={{ textDecoration: 'none', fontFamily: fonts.mono }}
        >
          REQUEST INVITE →
        </a>
      </header>

      {/* Main: animation + result */}
      <main style={{ flex: 1, padding: '32px 16px', maxWidth: 1100, margin: '0 auto', width: '100%' }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <div className="ug-mono" style={{ fontSize: 9, letterSpacing: '0.5em', color: colors.textMuted, marginBottom: 4 }}>
            VIRTUAL RACE · LIVE REPLAY
          </div>
          <div className="ug-mono" style={{ fontSize: 11, letterSpacing: '0.3em', color: colors.accent }}>
            {RACE_LABEL[r.raceType]?.toUpperCase() ?? r.raceType.toUpperCase()}
          </div>
        </div>

        <SpectateClient
          challengerLabel={challengerLabel}
          challengerShortLabel={chalV ? `${chalV.make} ${chalV.model}` : 'Challenger'}
          challengerCallsign={chalU?.callsign ?? null}
          challengerIsAdmin={chalU?.isModerator ?? false}
          challengerDrivetrain={chalV?.drivetrainOverride ?? 'UNKNOWN'}
          challengerPhotoUrl={chalPhoto?.urlFull ?? null}
          opponentLabel={opponentLabel}
          opponentShortLabel={oppV ? `${oppV.make} ${oppV.model}` : 'Opponent'}
          opponentCallsign={oppU?.callsign ?? null}
          opponentIsAdmin={oppU?.isModerator ?? false}
          opponentDrivetrain={oppV?.drivetrainOverride ?? 'UNKNOWN'}
          opponentPhotoUrl={oppPhoto?.urlFull ?? null}
          winner={winner as 'challenger' | 'opponent' | 'tie'}
          raceType={r.raceType}
          estimatedGap={r.estimatedGap ?? 0}
          challengerEt={r.challengerEstimatedEt}
          opponentEt={r.opponentEstimatedEt}
          challengerTrap={r.challengerTrapSpeed}
          opponentTrap={r.opponentTrapSpeed}
          summary={r.summary ?? ''}
          slug={slug}
          createdAt={r.createdAt}
        />
      </main>

      {/* Bottom CTA */}
      <footer
        style={{
          padding: '40px 24px 60px',
          borderTop: `1px solid ${colors.border}`,
          textAlign: 'center',
        }}
      >
        <div className="ug-mono" style={{ fontSize: 11, letterSpacing: '0.4em', color: colors.accent, marginBottom: 12, fontWeight: 700 }}>
          ∕∕ INVITE ONLY
        </div>
        <h2 style={{ fontSize: 24, margin: '0 0 16px', letterSpacing: '0.03em', maxWidth: 600, marginInline: 'auto' }}>
          A members-only garage for serious car people.
        </h2>
        <p style={{ fontSize: 13, color: colors.textMuted, maxWidth: 500, margin: '0 auto 24px', lineHeight: 1.6 }}>
          Real builds. Real specs. Race anyone in the gallery in a side-by-side simulation.
          We're letting in a small number of new members each week.
        </p>
        <a
          href="/"
          className="ug-btn ug-btn-primary"
          style={{ textDecoration: 'none', fontFamily: fonts.mono, letterSpacing: '0.4em' }}
        >
          REQUEST AN INVITE →
        </a>
      </footer>
    </div>
  );
}
